// 还需要加入eureka的配置 跟依赖
spring:
  mail:
    host: smtp.163.com
    port: 25
    protocol: smtp
    default-encoding: UTF-8
    username: // 你的邮箱
    password: // 邮箱 smtp密码
server:
  port: // 输入你想要的这个服务的端口号